### ISSUE TITLE
Add check to CI pipeline to ensure that ./lib is in sync with ./src

### ISSUE THREAD

**Issue by cronicc** [HorizenOfficial/zencashjs#34]
https://github.com/ZencashOfficial/zencashjs/commit/98a7327c9cc16b61438421ec7fc58dd63bbd4ab5 was forgotten in https://github.com/ZencashOfficial/zencashjs/pull/32 requiring a force push to fix. Not the nice way to do it but the alternative would have been to do another release v1.2.4 for this simple change.

So for the future we need a check in the CI pipeline to ensure `./lib` was regenerated before merging to master.

**Comment by jtoownus** [comment]
Is this still needed? Will add to the list of potential HDE go-live tasks if yes.

**Comment by angievi** [comment]
will review this issue with Cronic tomorrow and let you know @jtoownus

**Comment by salvatoretrimarchi** [comment]
@angievi @jtoownus Can I help you with this? You are using Travis. Can you give me more details. / 
Puedo ayudarles con esto?, estan usando Travis. Me pueden dar mas detalles.

**Comment by hamido007** [comment]
hey @salvatoretrimarchi 
that would be cool if you help me  concerning Travis and the issues im not familiar to travis

**Comment by cemgulvfx** [comment]
I can`t reached Travis Cl connection. Can you double check.

**Comment by jonahion** [comment]
Hello, I'd like to help with this issue if it's still open?
I'd suggest to do the check in a git hook as well so that, unless skipped with the -n flag, it gives a quick feedback

**Comment by jonahion** [comment]
@angievi @jtoownus, I have implemented the check in #41 
Please review

**Comment by angievi** [comment]
Hello! @jonahion , we will review and come back to you with an answer, in the mean time, thanks for your contribution!
Angie.

**Comment by Ukyithar** [comment]
How do use?

**Comment by Ukyithar** [comment]
will review this issue with Cronic tomorrow and let you know

**Comment by pawel-grzona** [comment]
cool, thank you both for the update

**Comment by jonahion** [comment]
cool, thank you both for the update :)

**Comment by jonahion** [comment]
Please review #44 instead of #41

**Comment by pawel-grzona** [comment]
@angievi, any news?

**Comment by jonahion** [comment]
Hi @angievi, thanks for your previous reply :)
Is there anything in the PR that needs improvement or explanation?

**Comment by angievi** [comment]
@jonahion nothing needed, the request for the bounty to be paid was sent. it should arrive soon.

thanks for contributing to HDE! :)

**Comment by jonahion** [comment]
@angievi, that's great, thanks!
it was a pleasure :)

**Comment by QAWSED4455** [comment]
Do it , great
