### ISSUE TITLE
How do use?

### ISSUE THREAD

**Issue by Ukyithar** [HorizenOfficial/zencashjs#43]
How do use?

_Originally posted by @Ukyithar in https://github.com/HorizenOfficial/zencashjs/issues/34#issuecomment-702340441_

**Comment by Ukyithar** [comment]
> How do use?
> 
> _Originally posted by @Ukyithar in [#34 (comment)](https://github.com/HorizenOfficial/zencashjs/issues/34#issuecomment-702340441)_

Hi guys

**Comment by Ukyithar** [comment]
https://github.com/HorizenOfficial/zencashjs/issues/43#issue-713112189

**Comment by PeaStew** [comment]
https://github.com/HorizenOfficial/zencashjs has instructions on how to use the library in your project
